name: 'Admire-Me'
description: 'Sends an email to the contributor with congratulating avatar image of the contributor.'
author: 'Prathamesh Giri'
branding:
  icon: 'sunrise'
  color: 'black'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
    branches:
      - master

jobs:
  deploy:
    env:
      GKEY: ${{ secrets.GKEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python
          pip install requests
          pip install smtp
          pip install pillow
          pip install numpy
      - uses: octokit/graphql-action@v2.x
        id: start_sending
        with:
          query: |
            query send($login:String!){
              user(login:$login){
                  login
                  avatarUrl
                  email
                }
              }
          login: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email
        run: |
          python ./AdmireMe.py '${{steps.start_sending.outputs.data}}' '${{github.repository}}'
